package com;

// Generated 25 Feb, 2015 3:24:59 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles", catalog = "assignment")
public class Roles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String role;

	public Roles() {
	}

	public Roles(String role) {
		this.role = role;
	}

	@Id
	@Column(name = "role", length = 35)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}
	public String toString(){
		return role;
	}

}
