package com;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 23 Feb, 2015 3:42:10 PM by Hibernate Tools 3.4.0.CR1

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users")
public class Users_new implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 16131L;
	@Id
	@Column(name="id")
	private int id;
	
	@Column(name="fname")
	private String fname;
	
	@Column(name="lname")
	private String lname;
	
	@Column(name="email")
	private String email;

	@Column(name="dob")
	private String dob;
	
	@Column(name="metadata")
	private String metadata;

	public Users_new() {
	}

	public Users_new(String fname, String lname, String email, String dob,
			String metadata) {
		this.fname = fname;
		this.lname = lname;
		this.email = email;
		this.dob = dob;
		this.metadata = metadata;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	public String getMetadata() {
		return this.metadata;
	}

	public void setMetadata(String metadata) {
		this.metadata = metadata;
	}

	public static  String toTableHeader() {
		
		return("<tr><th>id</th><th>FName</th><th>LName</th><th>E-mail</th><th>DOB</th><th>MetataDa</th></tr>");
		
		//.a TODO Auto-generated method stub
		
	}
	
public String toTableRow() {
		
		StringBuilder str=new StringBuilder();
		str.append("<tr><td>"+this.id+"</td><td>"+this.fname+"</td><td>"+this.lname+"</td><td>"+this.email+"</td><td>"+this.dob+"</td><td>"+this.metadata+"</td></tr>");
		
		//.a TODO Auto-generated method stub
		return str.toString();
	}
	
}
